# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2024-12-22 13:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_name', models.CharField(max_length=10, verbose_name='用户名')),
                ('telnumber', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^(?:0|86|＋?86)?1\\d{9}$', '手机号码错误')], verbose_name='手机号')),
                ('use_email', models.EmailField(max_length=20, verbose_name='邮箱')),
                ('usr_pwd', models.CharField(max_length=200, verbose_name='密码')),
            ],
        ),
    ]
