# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2024-12-24 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='use_email',
            new_name='usr_email',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='telnumber',
            new_name='usr_phone',
        ),
    ]
