# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2024-12-27 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.SmallIntegerField(choices=[(1, '#DC143C'), (2, '#00FA9A'), (3, '#FFFF00'), (4, '#FF8C00'), (5, '#48D1CC'), (6, '#C0C0C0')], default=1, max_length=20, verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='trancaction',
            name='count',
            field=models.IntegerField(default=1, help_text='0表示无期', verbose_name='数量(年)'),
        ),
    ]
