# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2024-12-24 13:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20241224_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='usr_phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^1[3-9]\\d{9}', '手机号码错误')], verbose_name='手机号'),
        ),
    ]
